
version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  dj:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
